### ISSUE TITLE
Cann't run some of given examples

### ISSUE THREAD

**Issue by zhaoyangluo** [chenmingzhang/SUTRASET#3]
Hi Chengming,

I met a problem when playing with SUTRASET. After compiling SUTRASET successfully, I copyed SUTRASET.exe into the ipnut files given in examples. Two examples can run (evaproation_salt_marsh and Fujimaki), whereas an error occurs for the rest (3D, Desaline_silt_loam and flume_drying). In addition, there is no error information in the smy file for these three examples, i.e., the smy file is empty. Coluld you please help me to sovle this problem? Thanks a lot.

Best regards,
Zhaoyang

**Comment by chenmingzhang** [comment]
Thanks for the feedback, just confirm, are you compiling sutraset in Windows or Linux?

**Comment by zhaoyangluo** [comment]
> Thanks for the feedback, just confirm, are you compiling sutraset in Windows or Linux?

I compiled it in Windows with VS 2019. Thanks.

**Comment by chenmingzhang** [comment]
Thanks for identifying this. it is now resolved in the latest [push](https://github.com/SUTRASET/SUTRASET/tree/b71d699b3158551d4304427653af08aace202b98).
We later added the relative permeability considering the film water contribution (important when saturation is low), and the input were incorporated in the ET.INP. While such input update was not incorporated into the two examples. 
Let me know if the fix works for you or not, so that i can close this issue.
Chenming

**Comment by zhaoyangluo** [comment]
Yes, it works now. Thank you very much. Zhaoyang
